### ISSUE TITLE
Adj Close key error in history() function

### ISSUE THREAD

**Issue by ishchat** [NayakwadiS/mftool#85]
Kudos on your work with this mftool.

When I try using history() function, I get the KeyError: 'Adj Close'. Is yfinance library not returning the Adj Close column?

Here is the traceback of the error:

Traceback (most recent call last):
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Adj Close'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Ishan\MutualFundsAnalysis\Analysis.py", line 33, in <module>
    df = mf.history("0P0000XVAA", start=None, end=None, period='3mo', as_dataframe=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\mftool\mftool.py", line 495, in history
    return get_Dataframe(response, as_dataframe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\mftool\mftool.py", line 479, in get_Dataframe
    df = df.drop(columns=['Open', 'High', 'Low','Adj Close','Volume'])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\frame.py", line 5581, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\indexes\multi.py", line 2419, in drop
    loc = self.get_loc(level_codes)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\indexes\multi.py", line 3040, in get_loc
    loc = self._get_level_indexer(key, level=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\indexes\multi.py", line 3391, in _get_level_indexer
    idx = self._get_loc_single_level_index(level_index, key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\indexes\multi.py", line 2980, in _get_loc_single_level_index      
    return level_index.get_loc(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ishan\miniconda3\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Adj Close'

**Comment by NayakwadiS** [comment]
I didn't get any error. It might be any configuration issue with conda.

![image](https://github.com/user-attachments/assets/8d074f36-2477-4b46-b0b2-322e6ada8872)
